WebApplication1/Pages/OurPages/AdminRedigeringAfBruger.cshtml.cs
// Frederik
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication1.Models;
using WebApplication1.Services;

namespace WebApplication1.Pages.OurPages
{
    public class AdminRedigeringAfBrugerModel : PageModel
    {
        public Bruger bruger {  get; set; } = new Bruger();
        public BrugerService brugerService { get; set; } = new BrugerService();

        public void OnGet()
        {

            brugerService = new BrugerService();
        }

        public IActionResult OnPostSletBruger(string email)
        {
            string authScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            var brugerService = new BrugerService();
            brugerService.DeleteByEmail(email);
            return Page();
        }

        public IActionResult OnPostRedigerBruger(string email)
        {
            string authScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            var brugerService = new BrugerService();
            brugerService.DeleteByEmail(email);
            return RedirectToPage("RedigerBrugerAdmin");
        }

    }
}

WebApplication1/Pages/OurPages/BookLokale.cshtml.cs
// Jeppe
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using static System.Runtime.InteropServices.JavaScript.JSType;
using WebApplication1.Models;
using WebApplication1.Services;
using System.Security.Claims;

namespace WebApplication1.Pages.OurPages
{
    public class BookLokaleModel : PageModel
    {
        [BindProperty] public int NewBookingStartHour { get; set; } = BookingService.EarliestAllowedBooking / 60;
        [BindProperty] public int NewBookingStartMinute { get; set; } = BookingService.EarliestAllowedBooking % 60;
        [BindProperty] public int NewBookingEndHour { get; set; } = BookingService.MaxBookingLength / 60;
        [BindProperty] public int NewBookingEndMinute { get; set; } = BookingService.MaxBookingLength % 60;


        public string? FejlMeddelse = null;

        public static string Skole { get; private set; }
        public static int _lokaleId = -1, _skoleId = -1;
        public static DateOnly _date;
        public IActionResult OnGet(int year = 1, int month = 1, int day = 1, int lokaleId = -1, int skoleId = -1)
        {
            System.Diagnostics.Debug.WriteLine($"y {year} m {month} d {day}");
            // check for invalid data
            if (lokaleId == -1 || skoleId == -1)
                return RedirectToPage("Booking");
            _lokaleId = lokaleId;
            _skoleId = skoleId;
            _date = new DateOnly(year, month, day);
            Skole = new SkoleService().Read(skoleId).Location;
            return Page();
        }
        public IActionResult OnPostBookLokale()
        {
            int start = NewBookingStartHour * 60 + NewBookingStartMinute;
            int end = start + NewBookingEndHour * 60 + NewBookingEndMinute;
            BookingTypeRepository bookingTypeRepository = new BookingTypeRepository();
            Booking newBooking = new Booking(-1, _date, start, end, LoginManager.LoggedInUser.Email, _lokaleId, _skoleId, bookingTypeRepository.Read(bookingTypeRepository.GetIdByName(BookingService.LokaleName)));
            FejlMeddelse = new BookingService().TryCreate(newBooking);
            return Page();
        }
        public IActionResult OnPostBookSmartboard()
        {
            int start = NewBookingStartHour * 60 + NewBookingStartMinute;
            int end = start + NewBookingEndHour * 60 + NewBookingEndMinute;
            BookingTypeRepository bookingTypeRepository = new BookingTypeRepository();
            Booking newBooking = new Booking(-1, _date, start, end, LoginManager.LoggedInUser.Email, _lokaleId, _skoleId, bookingTypeRepository.Read(bookingTypeRepository.GetIdByName(BookingService.SmartboardName)));
            FejlMeddelse = new BookingService().TryCreate(newBooking);
            return Page();
        }



        public List<TidsInterval> GetRoomAvailability(DateOnly date, string bookingType)
        {
            List<TidsInterval> availability = new List<TidsInterval>();
            // first we need to find every minute the room is available
            int earliestAllowedBooking = BookingService.EarliestAllowedBooking;
            int latestAllowedBooking = BookingService.LatestAllowedBooking;
            int[] minutesAvailable = new int[latestAllowedBooking - earliestAllowedBooking];
            List<Booking> bookings = new BookingService().ReadAll($"Dato='{date.Year + "-" + date.Month + "-" + date.Day}' AND LokaleId = {_lokaleId} AND SkoleId={_skoleId} AND Type={new BookingTypeRepository().GetIdByName(bookingType)}").ToList();
            foreach (var booking in bookings)
                for (int i = booking.TidFra > earliestAllowedBooking ? booking.TidFra : earliestAllowedBooking; i < (booking.TidTil < latestAllowedBooking ? booking.TidTil : latestAllowedBooking); i++)
                    minutesAvailable[i - earliestAllowedBooking]++;
            // get how many groups can be in the room at a given point in time
            int maxGroups = -1;
            if (bookingType == BookingService.LokaleName)
                maxGroups = new LokaleService().Read(_lokaleId).MaxGrupperAdGangen;
            else if (bookingType == BookingService.SmartboardName)
                maxGroups = 1;
            // we then need to convert them to an interval of minutes
            int available = minutesAvailable[0];
            int startInterval = 0;
            for (int i = 0; i < minutesAvailable.Length-1; i++)
            {
                if (minutesAvailable[i] != available)
                {
                    int endInterval = i - 1;
                    availability.Add(new TidsInterval(startInterval + earliestAllowedBooking, endInterval + earliestAllowedBooking, available == 0 ? TidsInterval.AvailableType.Available : (available < maxGroups ? TidsInterval.AvailableType.PartiallyAvailable : TidsInterval.AvailableType.NotAvailable))); //minutesAvailable gives "false" when it is available
                    startInterval = i;
                    available = minutesAvailable[i];
                }
            }
            // add final interval
            {
                int endInterval = minutesAvailable.Length-1;
                availability.Add(new TidsInterval(startInterval + earliestAllowedBooking, endInterval + earliestAllowedBooking, available == 0 ? TidsInterval.AvailableType.Available : (available < maxGroups ? TidsInterval.AvailableType.PartiallyAvailable : TidsInterval.AvailableType.NotAvailable)));
            }
            return availability;
        }

        public string FromMinutesToTime(int minutes)
        {
            int hours = minutes / 60;
            return $"{hours,2}:{minutes % 60, 2}";
        }

        public class TidsInterval
        {
            public int Start { get; }
            public int End { get; }
            public AvailableType Available { get; }
            public TidsInterval(int start, int end, AvailableType available)
            {
                Start = start;
                End = end;
                Available = available;
            }
            public enum AvailableType
            {
                Available,
                PartiallyAvailable,
                NotAvailable,
            }
        }
    }
}

WebApplication1/Pages/OurPages/Booking.cshtml.cs
// Jeppe
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication1.Models;
using WebApplication1.Services;
using System.Collections;
using System.Collections.Generic;
using Microsoft.AspNetCore.Routing;

namespace WebApplication1.Pages.OurPages
{
    public class BookingModel : PageModel
    {
        public int _skoleId;
        private SkoleService _skoleService;
		public string skole;
        [BindProperty]
        public DateOnly date { get; set; }
        private static DateOnly staticDate { get; set; }
        [BindProperty]
        public int StartIntervalHours { get; set; }
        [BindProperty]
        public int StartIntervalMinutes { get; set; }
        [BindProperty]
        public int EndIntervalHours { get; set; }
        [BindProperty]
        public int EndIntervalMinutes { get; set; }

        public int StartInterval { get; set; }
        public int EndInterval { get; set; }
        public BookingModel()
        {
            _skoleService = new SkoleService();
        }
        public IActionResult OnGet(int year = 0, int month = 1, int day = 1, int startInterval = BookingService.EarliestAllowedBooking, int endInterval = BookingService.LatestAllowedBooking)
        {
            // The first time you visit the page, it just defaults to the current day.
            if (year == 0)
            {
                DateOnly currentTime = DateOnly.FromDateTime(DateTime.Now);
                staticDate = new DateOnly(currentTime.Year, currentTime.Month, currentTime.Day);
                return RedirectToPage(null, new { year= currentTime.Year, month = currentTime.Month, day = currentTime.Day });
            }
            date = new DateOnly(year, month, day);
            // making sure the intervals make sense
            startInterval = startInterval < BookingService.EarliestAllowedBooking ? BookingService.EarliestAllowedBooking : startInterval;
            endInterval = endInterval > BookingService.LatestAllowedBooking ? BookingService.LatestAllowedBooking : endInterval;
            endInterval = endInterval < startInterval ? startInterval : endInterval;
            StartInterval = startInterval;
            StartIntervalHours = FromOnlyMinutesToHours(StartInterval);
            StartIntervalMinutes = FromOnlyMinutesToMinutes(StartInterval);

            EndInterval = endInterval;
            EndIntervalHours = FromOnlyMinutesToHours(EndInterval);
            EndIntervalMinutes = FromOnlyMinutesToMinutes(EndInterval);

            skole = _skoleService.Read(LoginManager.LoggedInUser.SkoleId).Location;
            _skoleId = LoginManager.LoggedInUser.SkoleId;
            return Page();
        }
        public IActionResult OnPostFilter(int startIntervalHours, int startIntervalMinutes, int endIntervalHours, int endIntervalMinutes)
        {
            staticDate = new DateOnly(date.Year, date.Month, date.Day);
            return RedirectToPage(null, new { year = date.Year, month = date.Month, day = date.Day, startInterval = FromHoursAndMinutesToOneInt(startIntervalHours, startIntervalMinutes), endInterval = FromHoursAndMinutesToOneInt(endIntervalHours, endIntervalMinutes) });
        }
        public IActionResult OnPostBookLokale(int lokaleIdPost, int skoleIdPost)
        {
            return RedirectToPage("BookLokale", new { year = staticDate.Year, month = staticDate.Month, day = staticDate.Day, lokaleId = lokaleIdPost, skoleId = skoleIdPost });
        }

        // converts from one int to represent time, to hours and minutes
        public static int FromOnlyMinutesToHours(int minutes)
        {
            return minutes / 60;
        }
        public static int FromOnlyMinutesToMinutes(int minutes)
        {
            return minutes % 60;
        }
        // converts from hours and minutes to one single int to represent time
        public int FromHoursAndMinutesToOneInt(int hours, int minutes)
        {
            return hours * 60 + minutes;
        }

        public Dictionary<int, List<Lokale>> GetRooms()
        {
            Dictionary<int, List<Lokale>> etageToRoomList = new Dictionary<int, List<Lokale>>();

            // get all bookings for the day
            List<Booking> bookings = new BookingService().ReadAll($"Dato='{date.Year+"-"+date.Month+"-"+date.Day}' AND SkoleId={_skoleId}").ToList();
            // go thorough all rooms
            foreach (var room in new LokaleService().ReadAll($"SkoleId={_skoleId}"))
            {
                // check if the room booked in the time interval
                bool[] timeAvailable = new bool[EndInterval - StartInterval];
                // we fill the timeAvailable array, with all the bookings that are connected to the room
                foreach (var booking in bookings.Where(book => book.LokaleId == room.Id))
                {
                    for (int i = booking.TidFra > StartInterval ? booking.TidFra : StartInterval; i < (booking.TidTil < EndInterval ? booking.TidTil : EndInterval); i++)
                        timeAvailable[i - StartInterval] = true;
                }
                int j;
                // then we go through the timeAvailable array, if it a value is "false", it is available at at least one minut of time, in the given interval
                for (j = 0; j < timeAvailable.Length; j++)
                    if (!timeAvailable[j])
                        break;
                // if j is equal to timeAvailable.Length, there wern't any available time
                if (j == timeAvailable.Length)
                    continue;
                // Make sure a key exists, for the floor
                if (!etageToRoomList.ContainsKey(room.Etage))
                    etageToRoomList.Add(room.Etage, new List<Lokale>());
                etageToRoomList[room.Etage].Add(room);
            }

            return etageToRoomList;
        }
    }
}

WebApplication1/Pages/OurPages/BrugerSide.cshtml.cs
// Jeppe og Roman
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication1.Services;

namespace WebApplication1.Pages.OurPages
{
    public class BrugerSideModel : PageModel
    {
        private readonly BookingService _bookingService;

        public BrugerSideModel()
        {
            _bookingService = new BookingService();
        }

        public IActionResult OnGet()
        {
            if (LogInModel.LoggedInBruger == null)
            {
                return RedirectToPage("LogIn");
            }
            return Page();
        }

        public IActionResult OnPostDeleteBooking(int bookingId)
        {

            _bookingService.Delete(bookingId);


            return RedirectToPage("BrugerSide");
        }

        public IActionResult OnPostSletBruger(string email)
        {
            LogInModel.LoggedInBruger = null;
            LoginManager.Logout();

            string authScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            HttpContext.SignOutAsync(authScheme);

            var brugerService = new BrugerService();
            brugerService.DeleteByEmail(email);
            return RedirectToPage("LogIn");
        }

    }
}

WebApplication1/Pages/OurPages/FAQ.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages.OurPages
{
    public class FAQModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApplication1/Pages/OurPages/KontaktOs.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages.OurPages
{
    public class KontaktOsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApplication1/Pages/OurPages/Logout.cshtml.cs
// Roman
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication1.Services;

namespace WebApplication1.Pages.OurPages
{
    public class LogoutModel : PageModel
    {
        public async Task<IActionResult> OnGet()
        {

            LogInModel.LoggedInBruger = null;
            LoginManager.Logout();


            string authScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            await HttpContext.SignOutAsync(authScheme);


            return RedirectToPage("/OurPages/Login");
        }
    }
}

WebApplication1/Pages/OurPages/RedigerBruger.cshtml.cs
// Frederik
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using WebApplication1.Models;
using WebApplication1.Services;

namespace WebApplication1.Pages.OurPages
{
    public class RedigerBrugerModel : PageModel
    {
        public BrugerService _brugerService { get; set; } = new BrugerService();

        [BindProperty]
        public Bruger _bruger { get; set; }
        [Display(Name = "Kodeord")]
        [BindProperty]
        public string Kodeord { get; set; }
        [Display(Name = "GentagKodeord")]
        [BindProperty]
        public string GentagKodeord { get; set; }
        [BindProperty]
        public string Message { get; set; }


        public IActionResult OnGet()
        {
            if (LogInModel.LoggedInBruger == null)
            { return RedirectToPage("/OurPages/LogIn"); }
            return Page();
        }
        public IActionResult OnPost()
        {
            _bruger = LogInModel.LoggedInBruger;
            if(GentagKodeord == Kodeord) 
            { 
            _bruger.Kodeord = Kodeord;
            _brugerService.Update(_bruger);
            Message = "Kode skiftet";
            return Page();
            } else
            {
                Message = $"Kodeord matcher ikke";
                return Page();
            }
        }
    }
}

WebApplication1/Pages/OurPages/RumTyper.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages.OurPages
{
    public class RumTyperModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApplication1/Pages/OurPages/AdminRedigeringAfBruger.cshtml
@* Frederik *@
@page
@model WebApplication1.Pages.OurPages.AdminRedigeringAfBrugerModel
@{
}

</style>
<head>

    <title>Liste over alle brugere</title>

</head>

<table class="table table-bordered table-hover table-striped table-opacity" width="60%">

    <tbody>
        <tr>
            <td style="width: 250px;">Navn</td>
            <td style="width: 250px;">Email</td>
            <td style="width: 250px;">Rolle</td>
            <td style="width: 250px;">SkoleId</td>
            <td style="width: 250px;">SletningsDato</td>
        </tr>

        @foreach(Models.Bruger bruger in Model.brugerService.ReadAll())
        {
            <tr>
                <td style="width: 250px;">@bruger.Navn</td>
                <td style="width: 250px;">@bruger.Email</td>
                <td style="width: 250px;">@bruger.Rolle.RolleNavn</td>
                <td style="width: 250px;">@bruger.SkoleId</td>
                <td style="width: 250px;">@bruger.SletningsDato</td>
                <td><a class="nav-link text-dark" asp-area="" asp-page="/OurPages/RedigerBrugerAdmin" asp-route-email="@bruger.Email">
                    <div class="card" style="width: 100%">
                            <button class="btn btn-primary">Rediger bruger</button>
                    </div>
                </a>
                </td>

                <td>
                    <form id="deleteUserForm" method="post">
                        <input asp-page-handler="SletBruger" asp-route-email="@bruger.Email" type="submit" onclick="confirmDelete()" value="Slet bruger" class="btn btn-danger">
                    </form>
                    <script>
                        function confirmDelete() {
                            if (confirm("Er du sikker på, at du gerne vil slette brugeren?")) {
                                
                                document.getElementById("deleteForm").submit();
                            } else {

                                return Page();
                            }
                        }
                    </script>
                </td>
            </tr>
        }
</table>

        

WebApplication1/Pages/OurPages/AdminSletBookning.cshtml
@* Jeppe *@
@page
@model WebApplication1.Pages.OurPages.AdminSletBookningModel
@{
}
<head>
    <style>
        table, th, td {
            border: 1px solid;
        }
    </style>
</head>
<h1>Slet en bookning</h1>

@* Select date & school *@
<form method="post">
    <div>
    <label asp-for="Date" class="control-label"></label>
    <input type="date" asp-for="Date" />
    @if (WebApplication1.Services.LoginManager.LoggedInUser.Rolle.RolleNavn == "admin")
    {
        string currentlySelectedSchool = new WebApplication1.Services.SkoleService().Read(Model.SchoolId)?.Location ?? "vælg en skole";
        <label asp-for="SchoolId" class="control-label"></label>
        <select name="SchoolId">
            <option value="@Model.SchoolId">@currentlySelectedSchool</option>
            @foreach (Models.Skole Skole in new WebApplication1.Services.SkoleService().ReadAll())
            {
                // We don't need the same school twice'
                if (Skole.Id == Model.SchoolId)
                {
                    continue;
                }
                <option value="@Skole.Id">@Skole.Location</option>
            }
        </select>
    }
    <input type="submit" value="Filtrer" asp-page-handler="Filter" />
    </div>
@* List all bookings *@

    @if (Model.Date < DateOnly.FromDateTime(DateTime.Now).AddDays(WebApplication1.Services.LoginManager.LoggedInUser.Rolle.DagesVarselIndenOverskrivelse.Value))
    {
        <p>Du kan desværre ikke slette andres bookinger, på denne dag (brugerne skal have længere varsel)</p>
    }
    else
    {
        <table>
            <tr>
                <td>Alle bookinger</td>
            </tr>
            <tr>
                <td>Lokale id</td>
                <td>Tid fra</td>
                <td>Tid til</td>
                <td>Personens email</td>
            </tr>
            @foreach (var booking in Model.GetAllBookings())
            {
                string gruppeMedlemRolle = new WebApplication1.Services.BrugerService().Read(booking.Gruppemedlem).Rolle.RolleNavn;
                <tr>
                    <td>@booking.LokaleId</td>
                    <td>@(booking.TidFra / 60):@(@booking.TidFra % 60)</td>
                    <td>@(booking.TidTil / 60):@(@booking.TidTil % 60)</td>
                    <td>@booking.Gruppemedlem (@gruppeMedlemRolle)</td>
                    <td>
                        <input asp-page-handler="DeleteBooking" asp-route-bookingId="@booking.Id" type="submit" value="Slet">
                    </td>
                </tr>
            }
        </table>
    }

</form> 

WebApplication1/Pages/OurPages/BookLokale.cshtml
@* Jeppe *@
@page
@model WebApplication1.Pages.OurPages.BookLokaleModel
@{
}
<head>

    <style>

        .BookButton input{
            type="color"


        }
 
    </style>
</head>

<h1>Lokale @BookLokaleModel._lokaleId på @BookLokaleModel.Skole</h1>

<div style="display:flex;">
    @{
        <div style="width:33%;">
            <p>Dette lokale er ledigt i følgende intervaller:</p>
            @foreach (var interval in Model.GetRoomAvailability(BookLokaleModel._date, WebApplication1.Services.BookingService.LokaleName))
            {
                string height = (interval.End - interval.Start) / 5 + "px";
                string backgroundColor = interval.Available == BookLokaleModel.TidsInterval.AvailableType.Available ? "green" : (interval.Available == BookLokaleModel.TidsInterval.AvailableType.PartiallyAvailable ? "yellow" :"red");
                <div style="background-color: @backgroundColor; height: @height; border: 1px solid #aaa; position:relative; min-height:30px;">
                    <span style="position:absolute; top:0px;">
                        <p>@Model.FromMinutesToTime(interval.Start) til @Model.FromMinutesToTime(interval.End)</p>
                    </span>
                </div>
            }
        </div>
        if (new WebApplication1.Services.LokaleService().Read(BookLokaleModel._lokaleId, BookLokaleModel._skoleId).HarSmartBoard)
        {
            <div style="width:33%;">
                <p>Lokalets smartboard er ledigt i følgende intervaller:</p>
                @foreach (var interval in Model.GetRoomAvailability(BookLokaleModel._date, WebApplication1.Services.BookingService.SmartboardName))
                {
                    string height = (interval.End - interval.Start) / 5 + "px";
                    string backgroundColor = interval.Available == BookLokaleModel.TidsInterval.AvailableType.Available ? "green" : (interval.Available == BookLokaleModel.TidsInterval.AvailableType.PartiallyAvailable ? "yellow" : "red");
                    <div style="background-color: @backgroundColor; height: @height; border: 1px solid #aaa; position:relative; min-height:30px;">
                        <span style="position:absolute; top:0px;">
                            <p>@Model.FromMinutesToTime(interval.Start) til @Model.FromMinutesToTime(interval.End)</p>
                        </span>
                    </div>
                }
            </div>
        } else
        {
            <p>Dette lokale har desværre ikke noget smartboard.</p>
        }
    }
</div>
@* Input when you want your booking to be at *@
<form method="post">
    <div>
        <p>Hvornår skal din bookning starte? </p>
        <p>Klokken <input asp-for="NewBookingStartHour" placeholder="timer" />:<input asp-for="NewBookingStartMinute" placeholder="minutter" /></p>
    </div>
    <div>
        <p>Hvor lang tid vil du booke lokalet?</p>
        <p><input asp-for="NewBookingEndHour" placeholder="timer" /> time(r) og <input asp-for="NewBookingEndMinute" placeholder="minutter" /> minut(ter)</p>
    </div>
    @* hvis der er en vejl meddelse *@
    @if (Model.FejlMeddelse != null)
    {
        <p>@Model.FejlMeddelse</p>
    }
    <div>
        <input type="submit" asp-page-handler="BookLokale" class="btn btn-warning" role="button" value="Book lokalet" />
        @if (new WebApplication1.Services.LokaleService().Read(BookLokaleModel._lokaleId, BookLokaleModel._skoleId).HarSmartBoard)
        {
            <input type="submit" asp-page-handler="BookSmartboard" class="BookButton" value="Book smartboard" />
        }
    </div>
</form>

WebApplication1/Pages/OurPages/Booking.cshtml
@* Jeppe *@
@page
@model WebApplication1.Pages.OurPages.BookingModel
@{
}

<h1>Alle lokaler (@Model.skole)</h1>
@* vælg dag og interval (filtre) *@
<head>
    <style>
        .TimeInput
        {
            width:50px;
        }
    </style>
</head>

<form method="post" asp-page-handler="Filter">
    <p>Start interval: <input class="TimeInput" asp-for="@Model.StartIntervalHours" />:<input class="TimeInput" asp-for="@Model.StartIntervalMinutes" /></p>
    <p>End interval:   <input class="TimeInput" asp-for="@Model.EndIntervalHours" />:<input class="TimeInput" asp-for="@Model.EndIntervalMinutes" /></p>
    <input type="date" asp-for="date" />
    <a asp-page="Booking"
       asp-route-startIntervalHours="@Model.StartIntervalHours Model.StartIntervalMinutes)" asp-route-startIntervalMinutes="@Model.StartIntervalHours Model.StartIntervalMinutes)"
       asp-route-endIntervalHours="@Model.StartIntervalHours Model.EndIntervalMinutes)" asp-route-endIntervalMinutes="@Model.EndIntervalHours Model.StartIntervalMinutes)">
        <input type="submit" value="Filtrer" />
    </a>
</form>



@* vis alle ledige rum *@

@{
    System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<WebApplication1.Models.Lokale>> floorAndRooms = Model.GetRooms();
    // we want to order the dictionary, based on the keys, so we go floor 0, floor 1. floor 2 etc.
    List<int> indecies = new List<int>();
    foreach (int floor in floorAndRooms.Keys)
        indecies.Add(floor);
    indecies.Sort();
    foreach(int floor in indecies)
    {
        if (floor == 0)
        {
            <h2>Stueetage</h2>
        }
        else
        {
            <h2>Etage @floor</h2>
        }
        <div style="border-style: solid;">
            @{
                var lokaler = floorAndRooms[floor];
                foreach (var lokale in lokaler)
                {
                        <form method="post" style="display:flex; justify-content:left;">

                            @{
                                string lokaleNummer = lokale.Id < 10 ? ("00" + lokale.Id) : (lokale.Id < 100 ? "0" + lokale.Id : (lokale.Id.ToString()));
                                <p>Lokale nummer: @lokaleNummer</p>
                            }
                            @if (lokale.HarSmartBoard)
                            {
                                <p>, dette lokale har et smartboard</p>
                            }
                            else
                            {
                                <p>, dette lokale har ikke noget smartboard</p>
                            }
                            <input type="submit" asp-page-handler="BookLokale" asp-route-lokaleIdPost="@lokale.Id" asp-route-skoleIdPost="@lokale.SkoleId" value="Book lokale">
                        </form>
                }
            }
        </div>
    }

}

WebApplication1/Pages/OurPages/Logout.cshtml
@page
@model WebApplication1.Pages.OurPages.LogoutModel
@{
}

WebApplication1/Pages/OurPages/RumTyper.cshtml
@page
@model WebApplication1.Pages.OurPages.RumTyperModel
@{
}